name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      - name: Get version tag
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "RELEASE_VERSION_NUMBER=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - name: Package
        id: package
        run: |
          EXPORT_DIR=windows_${{ env.RELEASE_VERSION_NUMBER }}_universal
          FILENAME=$EXPORT_DIR.tar.gz
          echo "FILENAME=$FILENAME" >> $GITHUB_ENV

          mkdir $EXPORT_DIR
          cp ./build/Release/windows $EXPORT_DIR/windows
          tar cf - $EXPORT_DIR/windows | gzip > $FILENAME
          echo ::set-output name=sha::"$(shasum -a 256 $FILENAME | awk '{printf $1}')"
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.FILENAME }}
