name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      - name: Get version tag
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "RELEASE_VERSION_NUMBER=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - name: Package
        id: package
        run: |
          EXPORT_DIR=windows_${{ env.RELEASE_VERSION_NUMBER }}_universal
          FILENAME=$EXPORT_DIR.tar.gz
          echo "FILENAME=$FILENAME" >> $GITHUB_ENV

          mkdir $EXPORT_DIR
          cp ./build/Release/windows $EXPORT_DIR/windows
          tar cf - $EXPORT_DIR/windows | gzip > $FILENAME
          echo ::set-output name=sha::"$(shasum -a 256 $FILENAME | awk '{printf $1}')"
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.FILENAME }}
      - name: Bump Homebrew
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_PAT }}
        run: |
          git config user.name "Release Bot"
          git config user.email "dev@vonlojewski.me"
          brew tap lowski/tap
          brew bump-formula-pr -f --version=${{ env.RELEASE_VERSION_NUMBER }} --no-browse --no-audit --write-only --commit \
          --sha256=${{ steps.package.outputs.sha }} \
          --url="https://github.com/lowski/windows/releases/download/${{ env.RELEASE_VERSION }}/${{ env.FILENAME }}" \
          lowski/tap/windows
          cd "$(brew --repository lowski/tap)"
          git remote set-url origin https://lowski:$HOMEBREW_GITHUB_API_TOKEN@github.com/lowski/homebrew-tap.git
          git push
